Add VersionDropdown component
the-guild-org/docs pull request #1888
Opened 2024-12-16 16:04 UTC by hasparus

https://github.com/user-attachments/assets/8c4e03e7-9a89-49fd-b69c-c7eeb0781f04

2024-12-17 06:31 UTC, dimaMachina commented on packages/components/src/components/hive-navigation/index.stories.tsx
> +          { label: 'v2', href: '#v2' },
```suggestion
          { label: 'Hive v1 Docs', href: '#v1' },
          { label: 'Hive v2 Docs', href: '#v2' },
```
similar to 
<img width="371" alt="image" src="https://github.com/user-attachments/assets/910f20e1-dad0-45c2-bd4e-7431e8317e20" />

(I want to see how it looks like in strorybook)

2024-12-18 05:09 UTC, dimaMachina requested changes
can you adjust styles so dropdown will take width from content? 🙏 
<img width="230" alt="image" src="https://github.com/user-attachments/assets/a9d62e52-bdc2-40c2-abe6-49e55626ced3" />

2024-12-30 17:37 UTC, hasparus commented
@dimaMachina Fixed it, but can't push :D I've sent you a git patch on Slack.

Just FYI I wanna merge this to `main` AND `v7` (possibly after some minor fixes).

2025-01-02 13:05 UTC, dotansimha approved these changes
lgtm, but let's wait for others to approve as well. thanks!

2025-01-02 13:05 UTC, dotansimha commented
@Urigo I think you had some opinion on how this dropdown should look like? can you please review as well?

2025-01-02 14:13 UTC, dimaMachina approved these changes
@hasparus I trust you that it looks good now, but we have permissions problems in this repo 😰
<img width="959" alt="image" src="https://github.com/user-attachments/assets/03a3253b-aec7-4812-a202-9e69d98b8c04" />

2025-01-02 20:05 UTC, saihaj submitted a review, later dismissed
right now this design doesn't make it visible enough on if I can switch version. I propose we add a Down caret and use a box. Examples to inspire from 

![CleanShot 2025-01-02 at 21 04 25@2x](https://github.com/user-attachments/assets/872247f9-d5d4-41b8-a116-72af0fd7c8a3)

![CleanShot 2025-01-02 at 21 04 55@2x](https://github.com/user-attachments/assets/85e0bde8-40e5-4f4f-852f-8c2978829797)

2025-01-03 14:24 UTC, hasparus commented on packages/components/src/components/version-dropdown.tsx
> +  chevronPosition?: 'left' | 'right';
This isn't supper elegant, but I think it actually make sense.

If we have v1, we'd have this on the right.
If we have "Mesh v1" or "1.0", it makes sense to put it on the left.

2025-01-03 14:28 UTC, dimaMachina approved these changes

2025-01-03 14:38 UTC, merged